apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: reneeins/api-server:5
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_HOST
              value: "mysql-service"
            - name: MYSQL_ROOT_PASSWORD
              value: "password"

---
apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 32639
  type: NodePort

